# Generated by Django 3.2.7 on 2023-11-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='MEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('desc', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('color', models.CharField(max_length=150, verbose_name='Color')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Disponible')),
                ('peso_neto', models.CharField(max_length=50, verbose_name='Peso neto, ml/gr')),
                ('codigo', models.BigIntegerField(verbose_name='Código')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mea.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'MEA',
                'verbose_name_plural': 'MEA',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True, verbose_name='Fecha del pedido')),
                ('pago', models.BooleanField(default=True)),
                ('nota', models.CharField(blank=True, max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mea.cliente', verbose_name='Cliente')),
                ('productos', models.ManyToManyField(to='mea.MEA', verbose_name='Prodcutos')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
