# Generated by Django 4.2 on 2023-04-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='MEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Disponible')),
                ('peso_neto', models.CharField(max_length=50, verbose_name='Peso neto, ml/gr')),
                ('codigo', models.BigIntegerField(verbose_name='Código')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mea.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'MEA',
                'verbose_name_plural': 'MEA',
            },
        ),
    ]
