# Generated by Django 4.2 on 2023-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0002_cliente_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido',
            field=models.ManyToManyField(to='mea.mea', verbose_name='Pedido'),
        ),
    ]
