# Generated by Django 4.2 on 2023-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0003_alter_pedido_options_remove_pedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='mea.mea', verbose_name='Prodcutos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
