# Generated by Django 3.2.7 on 2024-07-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0003_pedido_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproducto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
