# Generated by Django 3.2.7 on 2024-07-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0005_auto_20240724_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mea',
            options={'verbose_name': 'MEA (stock)', 'verbose_name_plural': 'MEA (stock)'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Stock de pedidos', 'verbose_name_plural': 'Stock de pedidos'},
        ),
    ]
