# Generated by Django 3.2.7 on 2024-07-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mea', '0006_auto_20240726_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mea',
            options={'verbose_name': 'MEA  (stock)', 'verbose_name_plural': 'MEA  (stock)'},
        ),
    ]
